version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: ovolstore-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
    networks:
      - ovolstore-network

  nginx:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    container_name: ovolstore-web
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - backend
    networks:
      - ovolstore-network

  mysql:
    image: mysql:8.0
    container_name: ovolstore-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ovolstore
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - ovolstore-network

  vite:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: ovolstore-vite
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - "5173:5173"
    volumes:
      - ./app:/var/www/html
      - /var/www/html/node_modules
    command: npm run dev -- --host
    networks:
      - ovolstore-network

networks:
  ovolstore-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
